"""Initial migration

Revision ID: 07e25f9a60c2
Revises: 
Create Date: 2025-05-30 03:27:49.516855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e25f9a60c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.String(length=100), nullable=True),
    sa.Column('wallet_balance', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('leverage', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('margin', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('group_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('security_question', sa.String(length=255), nullable=True),
    sa.Column('security_answer', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.Integer(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=False),
    sa.Column('referred_by_id', sa.Integer(), nullable=True),
    sa.Column('reffered_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referred_by_id'], ['demo_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'phone_number', 'user_type', name='_demo_email_phone_user_type_uc')
    )
    op.create_index(op.f('ix_demo_users_account_number'), 'demo_users', ['account_number'], unique=True)
    op.create_index(op.f('ix_demo_users_email'), 'demo_users', ['email'], unique=False)
    op.create_index(op.f('ix_demo_users_group_name'), 'demo_users', ['group_name'], unique=False)
    op.create_index(op.f('ix_demo_users_id'), 'demo_users', ['id'], unique=False)
    op.create_index(op.f('ix_demo_users_phone_number'), 'demo_users', ['phone_number'], unique=False)
    op.create_index(op.f('ix_demo_users_reffered_code'), 'demo_users', ['reffered_code'], unique=True)
    op.create_table('external_symbol_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=True),
    sa.Column('fix_symbol', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('digit', sa.DECIMAL(precision=10, scale=5), nullable=True),
    sa.Column('base', sa.String(length=10), nullable=True),
    sa.Column('profit', sa.String(length=10), nullable=True),
    sa.Column('margin', sa.String(length=50), nullable=True),
    sa.Column('contract_size', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('margin_leverage', sa.String(length=50), nullable=True),
    sa.Column('swap', sa.String(length=255), nullable=True),
    sa.Column('commission', sa.String(length=255), nullable=True),
    sa.Column('minimum_per_trade', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('steps', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('maximum_per_trade', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('maximum_per_login', sa.String(length=255), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=False),
    sa.Column('exchange_folder_id', sa.String(length=36), nullable=True),
    sa.Column('instrument_type', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_symbol_info_external_id'), 'external_symbol_info', ['external_id'], unique=False)
    op.create_index(op.f('ix_external_symbol_info_fix_symbol'), 'external_symbol_info', ['fix_symbol'], unique=True)
    op.create_index(op.f('ix_external_symbol_info_id'), 'external_symbol_info', ['id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('commision_type', sa.Integer(), nullable=False),
    sa.Column('commision_value_type', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('pip_currency', sa.String(length=255), nullable=True),
    sa.Column('show_points', sa.Integer(), nullable=True),
    sa.Column('swap_buy', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('swap_sell', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('commision', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('margin', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('spread', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('deviation', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('min_lot', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('max_lot', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('pips', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('spread_pip', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('sending_orders', sa.String(length=255), nullable=True),
    sa.Column('book', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'name', name='_symbol_name_uc')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=False)
    op.create_table('order_action_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=10), nullable=False),
    sa.Column('modify_id', sa.String(length=64), nullable=True),
    sa.Column('stoploss_id', sa.String(length=64), nullable=True),
    sa.Column('takeprofit_id', sa.String(length=64), nullable=True),
    sa.Column('stoploss_cancel_id', sa.String(length=64), nullable=True),
    sa.Column('takeprofit_cancel_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_action_history_id'), 'order_action_history', ['id'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('pips', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('spread_pip', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('market_price', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('show_points', sa.Integer(), nullable=True),
    sa.Column('profit_currency', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_id'), 'symbols', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.String(length=100), nullable=True),
    sa.Column('wallet_balance', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('leverage', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('margin', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('group_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('security_question', sa.String(length=255), nullable=True),
    sa.Column('security_answer', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.Integer(), nullable=True),
    sa.Column('fund_manager', sa.String(length=255), nullable=True),
    sa.Column('is_self_trading', sa.Integer(), nullable=False),
    sa.Column('id_proof', sa.String(length=255), nullable=True),
    sa.Column('id_proof_image', sa.String(length=255), nullable=True),
    sa.Column('address_proof', sa.String(length=255), nullable=True),
    sa.Column('address_proof_image', sa.String(length=255), nullable=True),
    sa.Column('bank_ifsc_code', sa.String(length=50), nullable=True),
    sa.Column('bank_holder_name', sa.String(length=255), nullable=True),
    sa.Column('bank_branch_name', sa.String(length=255), nullable=True),
    sa.Column('bank_account_number', sa.String(length=100), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=False),
    sa.Column('referred_by_id', sa.Integer(), nullable=True),
    sa.Column('reffered_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referred_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'phone_number', 'user_type', name='_email_phone_user_type_uc')
    )
    op.create_index(op.f('ix_users_account_number'), 'users', ['account_number'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_group_name'), 'users', ['group_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_index(op.f('ix_users_reffered_code'), 'users', ['reffered_code'], unique=True)
    op.create_table('demo_user_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('order_user_id', sa.Integer(), nullable=False),
    sa.Column('order_company_name', sa.String(length=255), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('order_status', sa.String(length=20), nullable=False),
    sa.Column('order_price', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('order_quantity', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('contract_value', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('margin', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('stop_loss', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('take_profit', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('close_price', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('net_profit', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('swap', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('commission', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('cancel_message', sa.String(length=255), nullable=True),
    sa.Column('close_message', sa.String(length=255), nullable=True),
    sa.Column('cancel_id', sa.String(length=64), nullable=True),
    sa.Column('close_id', sa.String(length=64), nullable=True),
    sa.Column('modify_id', sa.String(length=64), nullable=True),
    sa.Column('stoploss_id', sa.String(length=64), nullable=True),
    sa.Column('takeprofit_id', sa.String(length=64), nullable=True),
    sa.Column('stoploss_cancel_id', sa.String(length=64), nullable=True),
    sa.Column('takeprofit_cancel_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_user_id'], ['demo_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_user_orders_id'), 'demo_user_orders', ['id'], unique=False)
    op.create_index(op.f('ix_demo_user_orders_order_id'), 'demo_user_orders', ['order_id'], unique=True)
    op.create_table('money_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_money_requests_id'), 'money_requests', ['id'], unique=False)
    op.create_index(op.f('ix_money_requests_user_id'), 'money_requests', ['user_id'], unique=False)
    op.create_table('otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('demo_user_id', sa.Integer(), nullable=True),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['demo_user_id'], ['demo_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_demo_user_id'), 'otps', ['demo_user_id'], unique=False)
    op.create_index(op.f('ix_otps_id'), 'otps', ['id'], unique=False)
    op.create_index(op.f('ix_otps_user_id'), 'otps', ['user_id'], unique=False)
    op.create_table('rock_user_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('order_user_id', sa.Integer(), nullable=False),
    sa.Column('order_company_name', sa.String(length=255), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('order_status', sa.String(length=20), nullable=False),
    sa.Column('order_price', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('order_quantity', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('contract_value', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('margin', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('stop_loss', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('take_profit', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('close_price', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('net_profit', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('swap', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('commission', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('cancel_message', sa.String(length=255), nullable=True),
    sa.Column('close_message', sa.String(length=255), nullable=True),
    sa.Column('cancel_id', sa.String(length=64), nullable=True),
    sa.Column('close_id', sa.String(length=64), nullable=True),
    sa.Column('modify_id', sa.String(length=64), nullable=True),
    sa.Column('stoploss_id', sa.String(length=64), nullable=True),
    sa.Column('takeprofit_id', sa.String(length=64), nullable=True),
    sa.Column('stoploss_cancel_id', sa.String(length=64), nullable=True),
    sa.Column('takeprofit_cancel_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rock_user_orders_id'), 'rock_user_orders', ['id'], unique=False)
    op.create_index(op.f('ix_rock_user_orders_order_id'), 'rock_user_orders', ['order_id'], unique=True)
    op.create_table('user_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('order_user_id', sa.Integer(), nullable=False),
    sa.Column('order_company_name', sa.String(length=255), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('order_status', sa.String(length=20), nullable=False),
    sa.Column('order_price', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('order_quantity', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('contract_value', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('margin', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('stop_loss', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('take_profit', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('close_price', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('net_profit', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('swap', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('commission', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('cancel_message', sa.String(length=255), nullable=True),
    sa.Column('close_message', sa.String(length=255), nullable=True),
    sa.Column('cancel_id', sa.String(length=64), nullable=True),
    sa.Column('close_id', sa.String(length=64), nullable=True),
    sa.Column('modify_id', sa.String(length=64), nullable=True),
    sa.Column('stoploss_id', sa.String(length=64), nullable=True),
    sa.Column('takeprofit_id', sa.String(length=64), nullable=True),
    sa.Column('stoploss_cancel_id', sa.String(length=64), nullable=True),
    sa.Column('takeprofit_cancel_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_orders_id'), 'user_orders', ['id'], unique=False)
    op.create_index(op.f('ix_user_orders_order_id'), 'user_orders', ['order_id'], unique=True)
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('demo_user_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=255), nullable=True),
    sa.Column('order_quantity', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('is_approved', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=50), nullable=True),
    sa.Column('transaction_amount', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('transaction_time', sa.DateTime(), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['demo_user_id'], ['demo_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_demo_user_id'), 'wallets', ['demo_user_id'], unique=False)
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_index(op.f('ix_wallets_transaction_id'), 'wallets', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_transaction_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_demo_user_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_user_orders_order_id'), table_name='user_orders')
    op.drop_index(op.f('ix_user_orders_id'), table_name='user_orders')
    op.drop_table('user_orders')
    op.drop_index(op.f('ix_rock_user_orders_order_id'), table_name='rock_user_orders')
    op.drop_index(op.f('ix_rock_user_orders_id'), table_name='rock_user_orders')
    op.drop_table('rock_user_orders')
    op.drop_index(op.f('ix_otps_user_id'), table_name='otps')
    op.drop_index(op.f('ix_otps_id'), table_name='otps')
    op.drop_index(op.f('ix_otps_demo_user_id'), table_name='otps')
    op.drop_table('otps')
    op.drop_index(op.f('ix_money_requests_user_id'), table_name='money_requests')
    op.drop_index(op.f('ix_money_requests_id'), table_name='money_requests')
    op.drop_table('money_requests')
    op.drop_index(op.f('ix_demo_user_orders_order_id'), table_name='demo_user_orders')
    op.drop_index(op.f('ix_demo_user_orders_id'), table_name='demo_user_orders')
    op.drop_table('demo_user_orders')
    op.drop_index(op.f('ix_users_reffered_code'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_group_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_account_number'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_symbols_id'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_order_action_history_id'), table_name='order_action_history')
    op.drop_table('order_action_history')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_external_symbol_info_id'), table_name='external_symbol_info')
    op.drop_index(op.f('ix_external_symbol_info_fix_symbol'), table_name='external_symbol_info')
    op.drop_index(op.f('ix_external_symbol_info_external_id'), table_name='external_symbol_info')
    op.drop_table('external_symbol_info')
    op.drop_index(op.f('ix_demo_users_reffered_code'), table_name='demo_users')
    op.drop_index(op.f('ix_demo_users_phone_number'), table_name='demo_users')
    op.drop_index(op.f('ix_demo_users_id'), table_name='demo_users')
    op.drop_index(op.f('ix_demo_users_group_name'), table_name='demo_users')
    op.drop_index(op.f('ix_demo_users_email'), table_name='demo_users')
    op.drop_index(op.f('ix_demo_users_account_number'), table_name='demo_users')
    op.drop_table('demo_users')
    # ### end Alembic commands ###
