"""Add status field to Group with length constraint

Revision ID: 5ccc69349d6f
Revises: b43c66e9561c
Create Date: 2025-06-03 21:48:14.455568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ccc69349d6f'
down_revision: Union[str, None] = 'b43c66e9561c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demo_user_orders', sa.Column('status', sa.String(length=30), nullable=True))
    op.add_column('user_orders', sa.Column('status', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_orders', 'status')
    op.drop_column('demo_user_orders', 'status')
    # ### end Alembic commands ###
