"""add country column to users and demo_users

Revision ID: 67ff277a8555
Revises: 07e25f9a60c2
Create Date: 2025-06-02 00:45:11.134633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '67ff277a8555'
down_revision: Union[str, None] = '07e25f9a60c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demo_users', sa.Column('country', sa.String(length=100), nullable=True))
    op.drop_index(op.f('fix_symbol'), table_name='external_symbol_info')
    op.drop_index(op.f('idx_external_symbol_info_external_id'), table_name='external_symbol_info')
    op.drop_index(op.f('idx_external_symbol_info_fix_symbol'), table_name='external_symbol_info')
    op.create_index(op.f('ix_external_symbol_info_external_id'), 'external_symbol_info', ['external_id'], unique=False)
    op.create_index(op.f('ix_external_symbol_info_fix_symbol'), 'external_symbol_info', ['fix_symbol'], unique=True)
    op.create_index(op.f('ix_external_symbol_info_id'), 'external_symbol_info', ['id'], unique=False)
    op.drop_column('external_symbol_info', 'updated_at')
    op.drop_column('external_symbol_info', 'created_at')
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country')
    op.add_column('external_symbol_info', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('external_symbol_info', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.drop_index(op.f('ix_external_symbol_info_id'), table_name='external_symbol_info')
    op.drop_index(op.f('ix_external_symbol_info_fix_symbol'), table_name='external_symbol_info')
    op.drop_index(op.f('ix_external_symbol_info_external_id'), table_name='external_symbol_info')
    op.create_index(op.f('idx_external_symbol_info_fix_symbol'), 'external_symbol_info', ['fix_symbol'], unique=False)
    op.create_index(op.f('idx_external_symbol_info_external_id'), 'external_symbol_info', ['external_id'], unique=False)
    op.create_index(op.f('fix_symbol'), 'external_symbol_info', ['fix_symbol'], unique=True)
    op.drop_column('demo_users', 'country')
    # ### end Alembic commands ###
