"""add net_profit column to users and demo_users

Revision ID: b43c66e9561c
Revises: 67ff277a8555
Create Date: 2025-06-02 00:56:15.703597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43c66e9561c'
down_revision: Union[str, None] = '67ff277a8555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demo_users', sa.Column('net_profit', sa.DECIMAL(precision=18, scale=8), nullable=False))
    op.add_column('users', sa.Column('net_profit', sa.DECIMAL(precision=18, scale=8), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'net_profit')
    op.drop_column('demo_users', 'net_profit')
    # ### end Alembic commands ###
