"""Add crypto table

Revision ID: beca26b3e8b6
Revises: ef978394dd19
Create Date: 2025-06-30 22:12:12.429513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'beca26b3e8b6'
down_revision: Union[str, None] = 'ef978394dd19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('_symbol_name_uc'), table_name='groups1')
    op.drop_index(op.f('ix_groups_id'), table_name='groups1')
    op.drop_index(op.f('ix_groups_name'), table_name='groups1')
    op.drop_table('groups1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups1',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('commision_type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('commision_value_type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pip_currency', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('show_points', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('swap_buy', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('swap_sell', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('commision', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('margin', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('spread', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('deviation', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('min_lot', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('max_lot', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('pips', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('spread_pip', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('sending_orders', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('book', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_groups_name'), 'groups1', ['name'], unique=False)
    op.create_index(op.f('ix_groups_id'), 'groups1', ['id'], unique=False)
    op.create_index(op.f('_symbol_name_uc'), 'groups1', ['symbol', 'name'], unique=True)
    # ### end Alembic commands ###
