"""Add crypto table

Revision ID: c90ff05850ab
Revises: 6e566c344568
Create Date: 2025-06-30 05:10:53.990864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c90ff05850ab'
down_revision: Union[str, None] = '6e566c344568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('merchant_order_id', sa.String(length=255), nullable=False),
    sa.Column('base_amount', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('base_currency', sa.String(length=50), nullable=False),
    sa.Column('settled_currency', sa.String(length=50), nullable=False),
    sa.Column('network_symbol', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('transaction_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crypto_payments_id'), 'crypto_payments', ['id'], unique=False)
    op.create_index(op.f('ix_crypto_payments_merchant_order_id'), 'crypto_payments', ['merchant_order_id'], unique=True)
    op.create_index(op.f('ix_crypto_payments_user_id'), 'crypto_payments', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_favorite_symbols_id'), 'user_favorite_symbols', ['id'], unique=False)
    op.create_index(op.f('ix_user_favorite_symbols_symbol_id'), 'user_favorite_symbols', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_user_favorite_symbols_user_id'), 'user_favorite_symbols', ['user_id'], unique=False)
    op.create_foreign_key(None, 'user_favorite_symbols', 'symbols', ['symbol_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_favorite_symbols', type_='foreignkey')
    op.drop_index(op.f('ix_user_favorite_symbols_user_id'), table_name='user_favorite_symbols')
    op.drop_index(op.f('ix_user_favorite_symbols_symbol_id'), table_name='user_favorite_symbols')
    op.drop_index(op.f('ix_user_favorite_symbols_id'), table_name='user_favorite_symbols')
    op.drop_index(op.f('ix_crypto_payments_user_id'), table_name='crypto_payments')
    op.drop_index(op.f('ix_crypto_payments_merchant_order_id'), table_name='crypto_payments')
    op.drop_index(op.f('ix_crypto_payments_id'), table_name='crypto_payments')
    op.drop_table('crypto_payments')
    # ### end Alembic commands ###
