"""added more fields in orderactionhistory

Revision ID: d9bc96abf326
Revises: 25fc51109975
Create Date: 2025-06-10 21:35:32.980815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd9bc96abf326'
down_revision: Union[str, None] = '25fc51109975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('demo_user_orders', 'contract_value',
               existing_type=mysql.DECIMAL(precision=18, scale=8),
               nullable=True)
    op.alter_column('demo_user_orders', 'margin',
               existing_type=mysql.DECIMAL(precision=18, scale=8),
               nullable=True)
    op.add_column('order_action_history', sa.Column('order_id', sa.String(length=64), nullable=False))
    op.add_column('order_action_history', sa.Column('cancel_id', sa.String(length=64), nullable=True))
    op.add_column('order_action_history', sa.Column('close_id', sa.String(length=64), nullable=True))
    op.add_column('order_action_history', sa.Column('action_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_order_action_history_order_id'), 'order_action_history', ['order_id'], unique=False)
    op.alter_column('user_orders', 'contract_value',
               existing_type=mysql.DECIMAL(precision=18, scale=8),
               nullable=True)
    op.alter_column('user_orders', 'margin',
               existing_type=mysql.DECIMAL(precision=18, scale=8),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_orders', 'margin',
               existing_type=mysql.DECIMAL(precision=18, scale=8),
               nullable=True)
    op.alter_column('user_orders', 'contract_value',
               existing_type=mysql.DECIMAL(precision=18, scale=8),
               nullable=True)
    op.drop_index(op.f('ix_order_action_history_order_id'), table_name='order_action_history')
    op.drop_column('order_action_history', 'action_type')
    op.drop_column('order_action_history', 'close_id')
    op.drop_column('order_action_history', 'cancel_id')
    op.drop_column('order_action_history', 'order_id')
    op.alter_column('demo_user_orders', 'margin',
               existing_type=mysql.DECIMAL(precision=18, scale=8),
               nullable=True)
    op.alter_column('demo_user_orders', 'contract_value',
               existing_type=mysql.DECIMAL(precision=18, scale=8),
               nullable=True)
    # ### end Alembic commands ###
